# Generated by Django 3.0.6 on 2020-05-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroestacionamento',
            name='estacionamento',
        ),
        migrations.AddField(
            model_name='registroestacionamento',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Vaga'),
        ),
    ]
