# Generated by Django 3.0.6 on 2020-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vaga_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
